apiVersion: apps/v1
apiVersion: v1
kind: Service
metadata:
  name: student-survey-service
spec:
  selector:
    app: student-survey-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer